config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    CAT_COLORS = %w(black white orange brown).freeze

    validates :color, inclusion: CAT_COLORS
    validates :sex, inclusion: %w(M F)
    validates :birth_date, :color, :sex, :name, presence: true

    def age
        time_ago_in_words(birth_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            flash.now[:errors] = @cat.errors.full_messages
        render :new
        end
    end

    def index
        @cats = Cat.all
        render :index
    end

    def new
        @cat = Cat.new
        render :new
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def cat_params
        params.require(:cat).permit(:id, :name, :color, :sex, :birth_date, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
    <input type="hidden" name="_method" value="<%= method %>">

    <label>Name</label>
    <input 
        type="text"
        name="cat[name]"
        id="cat_name"
        value= "<%= cat.name%>"
    >
    <label>Birth Date </label>
    <input
        type="text"
        name="cat[birth_date]"
        id="cat_birth_date"
        value= "<%= cat.birth_date %>"
    >
    <input
        type="radio"
        name="cat[sex]"
        id="cat_sex_male"
        value="M"
        <%= cat.sex == "M" ? "checked" : "" %>
    >
    <label>Color</label>
    <select name="cat[color]" id="cat_color">
    <option disabled selected value="">Select a Color</option>
        <% Cat::CAT_COLORS.each do |color| %>
            <option 
            <%= cat.color == color ? "SELECTED" : "" %>
            value="<%= color %>">
            <%= color.upcase %> 
            </option>
        <%end%>
    </select>
    <label>M</label>
    <input
        type="radio"
        name="cat[sex]"
        id="cat_sex_female"
        value="F"
        <%= cat.sex == "F" ? "checked" : "" %>
    >
    <label>F</label>
    <br>

    <label>Description
        <textarea name="cat[description]"><%= cat.description%> </textarea>
    </label>

      <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
    <input type="submit" value="<%= submit_text %>">


</form>

app/views/cats/edit.html.erb
<h1>Edit Cat!</h1>

<%= render 'form', cat: @cat %>

app/views/cats/index.html.erb
<h1>Cats!!!!!</h1>

<ul>
    <% @cats.each do |cat| %>
        <li><%= link_to cat.name, cat_url(cat) %> </li>
    <% end %>
</ul>

app/views/cats/new.html.erb
<h1>New Cat!</h1>

<%= render 'form', cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<ul>
    <li>Age: <%=@cat.age %></li>
    <li>Color: <%=@cat.color%> </li>
    <li>Sex: <%=@cat.sex%> </li>
    <li>Description: <%@cat.description%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>